name: Build and push test docker image

on: [push]

env:
  DOCKER_IMAGE: 'csuvikg/cc-cicd-test:latest'

jobs:
  push-image-to-dockerhub:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: docker login
        run: docker login -u ${{secrets.DOCKER_USER}} -p ${{secrets.DOCKER_PASSWORD}}
      - name: build docker image
        run: docker build . -t $DOCKER_IMAGE
      - name: publish docker image
        run: docker push $DOCKER_IMAGE
